### ISSUE TITLE
Slack oauth instead of auth0

### ISSUE THREAD

**Issue by semenodp** [VandyHacks/proxima#102]
# User story

As a proxima user
When I access proxima
I want to login with slack
So that I don't need to remember 

# Requirements

- [ ] Create oauth slack app (ask Sayd for admin permissions)
- [ ] Use existing slack routes in this PR (https://github.com/VandyHacks/proxima/pull/48/files). You will need to provide `SLACK_CLIENT_ID` and `SLACK_CLIENT_SECRET`
- [ ] Create User table in DB
- [ ] Line 42 in `auth.ts`, check if User is part of VandyHacks workspace and persist his/her slack info to DB 
- [ ] Remove auth0 from frontend and have calls on backend routes for slack

***Story points:*** 4

**Comment by nkalupahana** [comment]
I think auth0 has a slack integration?

**Comment by semenodp** [comment]
> I think auth0 has a slack integration? Probably the easiest route to take tbh

You have to pay for it and we should get rid of auth0 anyways because free version has limit on number of users

**Comment by nkalupahana** [comment]
oh, alright makes sense -- didn't realize that!
