### ISSUE TITLE
Filter / group by committee applied for

### ISSUE THREAD

**Issue by aadibajpai** [VandyHacks/proxima#50]
# Description

As one of the dev directors, it would be more useful for me to be able to sort or filter by people who have the dev tag in their committee field. 

It appears the current ordering by clicking on the tab makes it ascending or descending depending on the number of committees a person has applied to which is largely not useful.

**Comment by semenodp** [comment]
This need to be addressed on the backend instead of frontend. Filtering and sorting is much more efficient when implementing on backend. Frontend solution is inefficient if there are 500+ applicants
