### ISSUE TITLE
search doesnt work 

### ISSUE THREAD

**Issue by aadarshjha** [VandyHacks/proxima#55]
**Describe the bug**
Search doesnt work rn, so im going to comment it out for now and then someone can pick it up later since we need the app for tomo. 

**To Reproduce**
1. Just go to search and see that it doesnt work lol

**Expected behavior**
I expected to be able to search 

**Screenshots**
No

**Desktop (please complete the following information):**
 Mac

**Smartphone (please complete the following information):**
from my computer

**Additional context**
n/a

**Comment by Chinchuluun1029** [comment]
Duplicate of #35
